services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    command: bundle exec rails server -b '0.0.0.0'
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - front/.env
    depends_on:
      - back
    command: npm run dev

volumes:
  db_data:
